name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'  # Allow MySQL to start without a password
          MYSQL_DATABASE: ${{ secrets.DB_NAME }}  # Use the database name from GitHub secrets
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost"
          --health-interval=30s
          --health-timeout=20s
          --health-retries=10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Wait for MySQL to be ready
        run: sleep 60  # Give MySQL time to initialize

      - name: List all running containers (for debugging)
        run: docker ps -a

      - name: Run tests
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ''  # Empty password since we're allowing no password
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_PORT: ${{ secrets.DB_PORT }}
        run: npm test

      - name: Check MySQL logs (if failed)
        if: failure()
        run: docker logs ${{ job.services.mysql.id }}
