name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Print environment variables for debugging
      run: |
        echo "DB_HOST: ${{ secrets.DB_HOST }}"
        echo "DB_USER: ${{ secrets.DB_USER }}"
        echo "DB_NAME: ${{ secrets.DB_NAME }}"
        echo "DB_PORT: ${{ secrets.DB_PORT }}"
        echo "DB_PASSWORD is set: ${{ secrets.DB_PASSWORD != '' }}"

    - name: Run Jest tests
      run: npm test
      env:
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASSWORD: ''
        DB_NAME: ${{ secrets.DB_NAME }}
        DB_PORT: ${{ secrets.DB_PORT }}
