name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: "true"  # Allow MySQL to run without a root password
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]  # Specify Node.js versions to test

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: npm

    - name: Install dependencies
      run: npm ci

    - name: Wait for MySQL to be ready
      run: |
        until mysqladmin ping --host=127.0.0.1 --port=3306 --silent; do
          echo "Waiting for MySQL to be ready..."
          sleep 5
        done

    - name: Set up test database
      run: node config/setup-test-db.js  # Ensure this script syncs your Sequelize models
      env:
        DB_HOST: 127.0.0.1
        DB_PORT: 3306
        DB_USER: root
        DB_PASSWORD: ""
        DB_NAME: health_check

    - name: Run database migrations (if needed)
      run: npx sequelize-cli db:migrate  # Run your Sequelize migrations
      env:
        DB_HOST: 127.0.0.1
        DB_PORT: 3306
        DB_USER: root
        DB_PASSWORD: ""
        DB_NAME: health_check

    - name: Run Jest tests (Unit & Integration)
      run: npm test
      env:
        APP_PORT: 8080
        DB_HOST: 127.0.0.1
        DB_PORT: 3306
        DB_USER: root
        DB_PASSWORD: ""
        DB_NAME: health_check

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: jest-results
        path: jest-output.xml

    - name: Upload coverage report
      if: success()
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: coverage/
