name: Packer Status Check

on:
  pull_request:
    branches:
      - main

jobs:
  packer-fmt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Packer
        run: |
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
          sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
          sudo apt-get update && sudo apt-get install packer -y

      - name: List directory contents (for debugging)
        run: ls -R

      # Zip the webapp folder located outside the repository root and save it directly into packer-template
      - name: Zip webapp folder directly into packer-template
        run: |
          zip -r ./packer-template/webapp.zip ../webapp  # Create zip directly in the packer-template directory

      - name: List contents of packer-template (ensure zip is there)
        working-directory: ./packer-template
        run: ls -la

      - name: Verify file existence before packer fmt
        working-directory: ./packer-template
        run: ls -la

      - name: Run packer fmt
        working-directory: ./packer-template
        run: packer fmt -check ubuntu-mysql.pkr.hcl

      - name: Fail if packer fmt modifies the template
        run: |
          git diff --exit-code || (echo "Packer fmt modified the packer template!" && exit 1)

  packer-validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Packer
        run: |
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
          sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
          sudo apt-get update && sudo apt-get install packer -y

      # Ensure the necessary files are in the packer-template folder
      - name: Ensure my-app.service and install_webapp.sh are present
        run: |
          cp my-app.service ./packer-template/
          cp install_webapp.sh ./packer-template/

      - name: Initialize Packer
        run: packer init ./packer-template/ubuntu-mysql.pkr.hcl

      - name: Run packer validate
        run: packer validate ./packer-template/ubuntu-mysql.pkr.hcl

      - name: Fail if packer validate fails
        run: |
          packer validate ./packer-template/ubuntu-mysql.pkr.hcl || (echo "Packer template validation failed!" && exit 1)
