name: Packer AMI Build

on:
  push:
    branches:
      - main

jobs:
  build-ami:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Packer
        uses: hashicorp/setup-packer@main
        with:
          version: "1.9.4"

      - name: Create webapp.zip
        run: |
          zip -r webapp.zip . -x "*.git*" "packer-template/*" ".github/*"
          mv webapp.zip packer-template/

      - name: List repository contents
        run: |
          echo "Root directory contents:"
          ls -la
          echo "packer-template directory contents:"
          ls -la packer-template

      - name: Check necessary files
        run: |
          for file in webapp.zip my-app.service install_webapp.sh; do
            if [ ! -f "packer-template/$file" ]; then
              echo "$file not found in packer-template directory"
              echo "Current directory structure:"
              find . -type f
              exit 1
            fi
          done

      # Debugging step to check the environment variables being passed
      - name: Debug Secret Variables
        run: |
          echo "DB_HOST: ${{ secrets.DB_HOST }}"
          echo "DB_USER: ${{ secrets.DB_USER }}"
          echo "DB_PASSWORD: [REDACTED]"
          echo "DB_NAME: ${{ secrets.DB_NAME }}"
          echo "DB_PORT: ${{ secrets.DB_PORT }}"
        continue-on-error: true  # Prevent job from failing for security reasons

      - name: Create variables file
        run: |
          cat << EOF > packer-template/variables.pkrvars.hcl
          aws_region = "us-east-1"
          instance_type = "t2.micro"
          ssh_username = "ubuntu"
          ami_users = "${{ secrets.DEMO_ACCOUNT_ID }}"
          db_host = "${{ secrets.DB_HOST }}"
          db_user = "${{ secrets.DB_USER }}"
          db_password = "${{ secrets.DB_PASSWORD }}"
          db_name = "${{ secrets.DB_NAME }}"
          db_port = "${{ secrets.DB_PORT }}"
          EOF

      - name: Initialize Packer
        run: packer init ./packer-template/ubuntu-mysql.pkr.hcl

      - name: Build AMI
        run: |
          cd packer-template
          packer build -var-file=variables.pkrvars.hcl ubuntu-mysql.pkr.hcl

      - name: Get AMI ID
        id: get-ami-id
        run: |
          AMI_ID=$(jq -r '.builds[-1].artifact_id' packer-template/manifest.json | cut -d ":" -f2)
          echo "ami_id=$AMI_ID" >> $GITHUB_OUTPUT

      - name: Share AMI with DEMO account
        run: |
          aws ec2 modify-image-attribute \
            --image-id ${{ steps.get-ami-id.outputs.ami_id }} \
            --launch-permission "Add=[{UserId=${{ secrets.DEMO_ACCOUNT_ID }}}]"

      - name: Clean up
        if: always()
        run: |
          rm -f packer-template/webapp.zip
