name: Packer Build and Validation

on:
  pull_request:
    branches:
      - main  # This will trigger on PRs to main only

jobs:
  packer-check:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up Packer on the runner machine
    - name: Set up Packer
      uses: hashicorp/setup-packer@v2
      with:
        version: '1.7.10'  # Packer version to use

    # Step 3: Initialize Packer (This installs required plugins, like the Amazon plugin)
    - name: Initialize Packer
      run: packer init ./packer-template/ubuntu-mysql.pkr.hcl  # Adjust the path to your HCL file

    # Step 4: Validate Packer template (Check if the Packer file is correctly structured)
    - name: Validate Packer template
      run: packer validate ./packer-template/ubuntu-mysql.pkr.hcl  # Adjust the path if needed

    # Step 5: Check for formatting issues in the Packer template
    - name: Format Packer template
      run: packer fmt -check ./packer-template/ubuntu-mysql.pkr.hcl  # Adjust the path if needed

    # Step 6: Post checkout steps (GitHub cleanup)
    - name: Post Checkout code
      run: |
        echo "Post-job cleanup complete"
