name: Packer Status Check

on:
  pull_request:
    branches:
      - main

jobs:
  packer-check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Packer
      uses: hashicorp/setup-packer@v2  # Updated to the latest version
      with:
        version: '1.7.10'  # Specify the desired Packer version

    - name: Validate Packer template
      run: packer validate your-packer-template.json

    - name: Format Packer template
      run: packer fmt -check your-packer-template.json

