name: Packer Status Check

on:
  pull_request:
    branches: [main]

jobs:
  packer-status-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Packer
        uses: hashicorp/setup-packer@main
        with:
          version: "1.9.4"  # Specify the Packer version you want to use

      - name: Packer fmt check
        run: |
          packer fmt -check -diff packer-template/ubuntu-mysql.pkr.hcl
        continue-on-error: false

      - name: Verify packer-template contents
        run: |
          echo "Contents of packer-template directory:"
          ls -la packer-template

      - name: Packer validate
        run: |
          cd packer-template
          packer init ubuntu-mysql.pkr.hcl
          packer validate -syntax-only ubuntu-mysql.pkr.hcl
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        continue-on-error: false

      - name: Prevent merge on failure
        if: failure()
        run: |
          echo "Packer validation failed. This pull request cannot be merged."
          exit 1