name: Packer AMI Build

on:
  push:
    branches:
      - main

jobs:
  build-ami:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Packer
        uses: hashicorp/setup-packer@main
        with:
          version: "1.9.4"

      - name: Create webapp.zip
        run: |
          zip -r webapp.zip . -x "*.git*" "packer-template/*" ".github/*"
          mv webapp.zip packer-template/

      - name: Create variables file
        run: |
          cat << EOF > packer-template/variables.pkrvars.hcl
          aws_region = "us-east-1"
          instance_type = "t2.small"
          ssh_username = "ubuntu"
          source_ami = "ami-0866a3c8686eaeeba"
          subnet_id = "${{ secrets.SUBNET_ID }}"
          EOF

      - name: Initialize Packer
        run: packer init ./packer-template/ubuntu-mysql.pkr.hcl

      - name: Validate Packer Template
        run: |
          cd packer-template
          packer validate -var-file=variables.pkrvars.hcl \
            ubuntu-mysql.pkr.hcl

      - name: Build AMI
        run: |
          cd packer-template
          packer build -machine-readable -var-file=variables.pkrvars.hcl \
            ubuntu-mysql.pkr.hcl

      - name: Verify manifest.json
        run: |
          if [ ! -f packer-template/manifest.json ]; then
            echo "Error: manifest.json not found!"
            exit 1
          else
            echo "manifest.json found. Proceeding with the workflow."
          fi

      - name: Get AMI ID
        id: get-ami-id
        run: |
          AMI_ID=$(jq -r '.builds[-1].artifact_id' packer-template/manifest.json | cut -d ":" -f2)
          echo "ami_id=$AMI_ID" >> $GITHUB_OUTPUT
          echo "AMI_ID=$AMI_ID" >> $GITHUB_ENV

      - name: Export AMI ID
        run: echo "AMI_ID=${{ env.AMI_ID }}"

      - name: Clean up
        if: always()
        run: |
          rm -f packer-template/webapp.zip packer-template/variables.pkrvars.hcl

      - name: Debug Output
        if: failure()
        run: |
          echo "Packer template contents:"
          cat packer-template/ubuntu-mysql.pkr.hcl
          echo "Variables file contents:"
          cat packer-template/variables.pkrvars.hcl
