name: Packer Validate

on:
  pull_request:
    branches:
      - main

jobs:
  packer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Create the webapp.zip from the webapp folder while excluding unnecessary files
      - name: Zip folder creation
        run: |
          zip -r packer-template/webapp.zip ./webapp -x ".git*" ".github*" "node_modules*"
      
      # Copy the necessary files to the packer-template directory
      - name: Copy service and script files
        run: |
          cp my-app.service packer-template/
          cp install_webapp.sh packer-template/

      # List the contents of packer-template to ensure all files are in place
      - name: List Directory Contents After Copy
        run: ls -al packer-template

      # Initialize and Validate Packer template
      - name: Initialize and Validate Packer
        run: |
          cd packer-template
          packer init ubuntu-mysql.pkr.hcl
          packer fmt -check ubuntu-mysql.pkr.hcl
          packer validate ubuntu-mysql.pkr.hcl
