name: Packer AMI Build

on:
  push:
    branches:
      - main

jobs:
  build-ami:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Packer
        uses: hashicorp/setup-packer@main
        with:
          version: "1.9.4"

      - name: Create .env file
        run: |
          echo "AWS_REGION=us-east-1" >> .env
          echo "SOURCE_AMI=$(aws ec2 describe-images --owners amazon --filters 'Name=name,Values=ubuntu/images/hvm-ssd/ubuntu-jammy-24.04-amd64-server-*' 'Name=state,Values=available' --query 'sort_by(Images, &CreationDate)[-1].ImageId' --output text)" >> .env
          echo "INSTANCE_TYPE=t2.micro" >> .env
          echo "SSH_USERNAME=ubuntu" >> .env
          echo "AMI_USERS=${{ secrets.DEMO_ACCOUNT_ID }}" >> .env
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
          echo "DB_USER=${{ secrets.DB_USER }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
          echo "DB_PORT=${{ secrets.DB_PORT }}" >> .env

      - name: Initialize Packer
        run: packer init ./packer-template/ubuntu-mysql.pkr.hcl

      - name: Build AMI
        run: |
          packer build \
            -var-file=.env \
            ./packer-template/ubuntu-mysql.pkr.hcl

      - name: Get AMI ID
        id: get-ami-id
        run: |
          AMI_ID=$(jq -r '.builds[-1].artifact_id' manifest.json | cut -d ":" -f2)
          echo "::set-output name=ami_id::$AMI_ID"

      - name: Share AMI with DEMO account
        run: |
          aws ec2 modify-image-attribute \
            --image-id ${{ steps.get-ami-id.outputs.ami_id }} \
            --launch-permission "Add=[{UserId=${{ secrets.DEMO_ACCOUNT_ID }}}]"