name: Packer Status Check

on:
  pull_request:
    branches:
      - main

jobs:
  packer-fmt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step to generate webapp.zip from the contents of the webapp folder
      - name: Generate webapp.zip
        run: zip -r webapp.zip ./webapp  # Adjust the path to your webapp folder

      # Ensure the webapp.zip is available
      - name: List directory contents
        run: ls -R

      - name: Run packer fmt
        run: packer fmt -check ./packer-template/ubuntu-mysql.pkr.hcl  # Path to the file

      - name: Fail if packer fmt modifies the template
        run: |
          git diff --exit-code || (echo "Packer fmt modified the packer template!" && exit 1)

  packer-validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step to generate webapp.zip from the contents of the webapp folder
      - name: Generate webapp.zip
        run: zip -r webapp.zip ./webapp  # Adjust the path to your webapp folder

      # Ensure the webapp.zip is available
      - name: List directory contents
        run: ls -R

      - name: Install Packer
        run: |
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
          sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
          sudo apt-get update && sudo apt-get install packer -y

      - name: Initialize Packer
        run: packer init ./packer-template/ubuntu-mysql.pkr.hcl  # Correct path

      - name: Run packer validate
        run: packer validate ./packer-template/ubuntu-mysql.pkr.hcl  # Correct path

      - name: Fail if packer validate fails
        run: |
          packer validate ./packer-template/ubuntu-mysql.pkr.hcl || (echo "Packer template validation failed!" && exit 1)
