name: Packer Status Check

on:
  pull_request:
    branches:
      - main  # Trigger the action on pull requests to the main branch

jobs:
  packer-fmt:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Packer
        run: |
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
          sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
          sudo apt-get update && sudo apt-get install packer -y

      # Step to verify the directory contents to ensure the files are present
      - name: Check directory contents
        run: ls -R

      - name: Run packer fmt
        run: packer fmt -check ./packer-template/ubuntu-mysql.pkr.hcl

      - name: Fail if packer fmt modifies the template
        run: |
          git diff --exit-code || (echo "Packer fmt modified the template!" && exit 1)

  packer-validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Packer
        run: |
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
          sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
          sudo apt-get update && sudo apt-get install packer -y

      - name: Check directory contents
        run: ls -R

      - name: Initialize Packer
        run: packer init ./packer-template/ubuntu-mysql.pkr.hcl

      - name: Validate Packer template
        run: packer validate ./packer-template/ubuntu-mysql.pkr.hcl

      - name: Fail if Packer validation fails
        run: |
          packer validate ./packer-template/ubuntu-mysql.pkr.hcl || (echo "Packer template validation failed!" && exit 1)
