name: Packer Status Check

on:
  pull_request:
    branches:
      - main

jobs:
  packer-check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Packer
      uses: hashicorp/setup-packer@v2
      with:
        version: '1.7.10'  # Packer version

    - name: Validate Packer template
      run: packer validate packer-template/ubuntu-mysql.pkr.hcl  # Update the correct file name

    - name: Format Packer template
      run: packer fmt -check packer-template/ubuntu-mysql.pkr.hcl  # Update the correct file name


