name: Packer Status Check

on:
  pull_request:
    branches:
      - main

jobs:
  packer-fmt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Packer
        run: |
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
          sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
          sudo apt-get update && sudo apt-get install packer -y

      - name: List directory contents (for debugging)
        run: ls -R

      # Zip the webapp folder and move the webapp.zip to packer-template
      - name: Zip webapp folder
        run: |
          zip -r webapp.zip ../webapp  # Zipping the folder from the parent directory
          mv webapp.zip ./packer-template/webapp.zip
        working-directory: ./packer-template

      - name: List contents of packer-template (ensure zip is there)
        run: ls -R ./packer-template

      - name: Run packer fmt
        run: packer fmt -check ./packer-template/ubuntu-mysql.pkr.hcl

      - name: Fail if packer fmt modifies the template
        run: |
          git diff --exit-code || (echo "Packer fmt modified the packer template!" && exit 1)

  packer-validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Packer
        run: |
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
          sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
          sudo apt-get update && sudo apt-get install packer -y

      - name: Initialize Packer
        run: packer init ./packer-template/ubuntu-mysql.pkr.hcl

      - name: Run packer validate
        run: packer validate ./packer-template/ubuntu-mysql.pkr.hcl

      - name: Fail if packer validate fails
        run: |
          packer validate ./packer-template/ubuntu-mysql.pkr.hcl || (echo "Packer template validation failed!" && exit 1)
