name: Packer AMI Build

on:
  push:
    branches:
      - main

jobs:
  build-ami:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Packer
        uses: hashicorp/setup-packer@main
        with:
          version: "1.9.4"

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Create webapp.zip
        run: |
          zip -r webapp.zip . -x "*.git*" "packer-template/*" ".github/*"
          mv webapp.zip packer-template/

      - name: List repository contents
        run: |
          echo "Root directory contents:"
          ls -la
          echo "packer-template directory contents:"
          ls -la packer-template

      - name: Check necessary files
        run: |
          for file in webapp.zip my-app.service install_webapp.sh; do
            if [ ! -f "packer-template/$file" ]; then
              echo "$file not found in packer-template directory"
              echo "Current directory structure:"
              find . -type f
              exit 1
            fi
          done

      - name: Create variables file
        run: |
          cat << EOF > packer-template/variables.pkrvars.hcl
          aws_region = "us-east-1"
          instance_type = "t2.small"
          ssh_username = "ubuntu"
          source_ami = "ami-0866a3c8686eaeeba"
          subnet_id = "subnet-063beaf3ff4e82a4d"
          EOF

      - name: Initialize Packer
        run: packer init ./packer-template/ubuntu-mysql.pkr.hcl

      - name: Validate Packer Template
        run: |
          cd packer-template
          packer validate -var-file=variables.pkrvars.hcl ubuntu-mysql.pkr.hcl

      - name: Build AMI
        run: |
          cd packer-template
          packer build -debug -var-file=variables.pkrvars.hcl ubuntu-mysql.pkr.hcl

      - name: Get AMI ID
        id: get-ami-id
        run: |
          AMI_ID=$(jq -r '.builds[-1].artifact_id' packer-template/manifest.json | cut -d ":" -f2)
          echo "ami_id=$AMI_ID" >> $GITHUB_OUTPUT
        
      - name: Output AMI ID
        run: |
          echo "Built AMI ID: ${{ steps.get-ami-id.outputs.ami_id }}"

      - name: Clean up
        if: always()
        run: |
          rm -f packer-template/webapp.zip

      - name: Debug Output
        if: failure()
        run: |
          echo "Packer template contents:"
          cat packer-template/ubuntu-mysql.pkr.hcl
          echo "Variables file contents:"
          cat packer-template/variables.pkrvars.hcl
          echo "install_webapp.sh contents:"
          cat packer-template/install_webapp.sh
          echo "my-app.service contents:"
          cat packer-template/my-app.service