name: Packer AMI Build

on:
  push:
    branches:
      - main

jobs:
  build-ami:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Specify your region

      - name: Install Packer
        uses: hashicorp/setup-packer@v1

      - name: Build AMI with Packer
        run: |
          packer build your-packer-template.json

      - name: Post AMI ID
        run: |
          echo "Packer AMI Build Complete"
